### ISSUE TITLE
Where should my custom sources_template live?

### ISSUE THREAD

**Issue by dbernstein** [mlehner616/mlehner616-puppet-sumo#4]
Hi Mike, 

I've got a module that references mlehner616-puppet-sumo in its manifests/site.pp file.  I'm not sure where I should put my custom sources_template file in sumo to be able to find it.  The only thing I've been able to do to get things to work is to copy my custom file to /etc/puppet/modules/sumo/templates/sumo.json.erb before running puppet apply. I've tried various places in my module's tree without luck. Please advise. 

Thanks  --db

**Comment by mlehner616** [comment]
In a perfect world, everything should be parameterized. I didn't have time to write more low level manifests to pull the sources apart. Mostly because I don't use those at the moment (the rest get configured through the Sumo UI).

Anyway, you will probably want to look into the Role/Profile architectures if you haven't already. Something like this could be configured in a profile called site-sumo (or whatever you want to name it). Then that profile may look something like the following (Note: I did not test this, but it should get close). There are many other ways to do this that may be better for your use-case. The example in the documentation is using hiera and referencing a custom file _added_ directly into the templates directory. Although it's best not to modify third party modules if you can avoid it. You shouldn't have to overwrite the existing file to get this to work but you do need to set that parameter `sumo::sources_template`.

## directory structure

```
/etc/puppetlabs/puppet/:
  modules/profile/:
    templates/:
      my_custom_sources.json.erb
    manifests/:
      sumo.pp
```

## modules/profile/manifests/sumo.pp

``` (Puppet)
# Class: profile::sumo
# Wraps the mlehner616-sumo module
class profile::sumo {
  class { '::sumo':
    #...some parameters...,
    sources_template: 'puppet:///modules/profile/my_custom_sources.json.erb',
  }
}
```

**Comment by mlehner616** [comment]
@dbernstein,

Did any of the above info help or guide you to a solution that works for you?

**Comment by dbernstein** [comment]
Hi Mike, 

Thanks for the thorough response.  I haven't had a chance to try it yet.   The hack that I initially used was working and I needed to move on.  But I plan to give your suggestion a shot shortly. I'll let you know how it goes.

**Comment by mlehner616** [comment]
Ok, I'll go ahead and close this issue for now. You're welcome to start up a new one if you encounter any other issues.
